baseURL = "https://shyaginuma.github.io/portfolio/"
languageCode = "en-us"
title = "yaginuuun blog"
theme = "ezhil"
publishDir = "docs" # github pages用の設定
enableEmoji = true

copyright = "© 2020- Shinya YAGINUMA"
googleAnalytics = "UA-172479959-1"
disqusShortname = "yaginuuun-blog"

# ブログの設定
paginate = 10
summaryLength = 20

[params]
    subtitle = ""
    mainSections = ["posts"]
    featherIconsCDN = true
    customCSS = "css/custom.css"
    customDarkCSS = "css/custom-dark.css"
    favicon = "icons/myicon.png"

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "About me"
url = "/about"
weight = 2

[[menu.main]]
name = "Work history"
url = "/work_history"
weight = 3

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/shyaginuma"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/yaginuuun"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/shinya-yaginuma"

[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto:yaginuuun@gmail.com"

[taxonomies]
   tag = "tags"